### PR TITLE
Remove 'see' from Haskell

### PR DESCRIPTION
**Pull request by ShalokShalom**
Idk what it did there

### CODE REVIEW

**Comment by Vivraan** [comment]
@ShalokShalom I am usually not active on GitHub -- could you tag me on Discord if you have patches?

**Review by Vivraan — APPROVED** [review]

**Comment by ShalokShalom** [comment]
> @ShalokShalom I am usually not active on GitHub -- could you tag me on Discord if you have patches?

I used to have commit rights. Do you think, they are appropriate again?

**Comment by Vivraan** [comment]
Please check if you can commit again.

**Comment by ShalokShalom** [comment]
thanks

**Pull request merged**
