### PR TITLE
Add Haxe/C# project

### PR DESCRIPTION
**Pull request by ibilon**
Adds an Haxe/C# entry following #36

### CODE REVIEW

**Comment by ShalokShalom** [comment]
What means 'Haxe/C# externs'?
Can you improve that wording?

**Comment by ibilon** [comment]
I meant binding, I've updated the description, should be better now.

**Review by Vivraan — APPROVED** [review]

**Comment by ibilon** [comment]
@Vivraan any changes missing?

**Comment by Vivraan** [comment]
@ShalokShalom merging this.

**Pull request merged**
